version: '3.5'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ~/data/db:/data/db

  mongoClientTemp:
    image: mongo:latest
    container_name: mongoClientTemp
    links:
      - mongo:mongo
    command: >
      bash -c "sleep 1 && mongo --host mongo --eval 
      \"db.getSiblingDB('admin').createUser({user:'datadog', pwd:'ddpassword', 
      roles:[{role:'read',db:'admin'},{role:'clusterMonitor',db:'admin'},
      {role:'read',db:'local'}]});\" "
    depends_on:
      - mongo

  datadog:
    build: datadog
    links:
      - mongo
    environment:
      - DD_API_KEY=4b95c86418ff04b87fd79f2831944a46
    ports:
      - '8126:8126'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
